import turtle
t = turtle.Turtle()
t.speed(speed=0)
t.color('black')
t.fillcolor('black')
t.begin_fill()
for _ in range(16):
    t.left(22.5)
    t.circle(120)
t.end_fill()
t.color('red')
t.fillcolor('red')
t.begin_fill()
for _ in range(16):
    t.left(22.5)
    t.fd(170)
    t.left(90)
    t.fd(170)
    t.left(90)
    t.fd(170)
    t.left(90)
    t.fd(170)
t.end_fill()
t.left(11.25)
t.color('orange')
t.fillcolor('orange')
t.begin_fill()
for _ in range(16):
    t.left(22.5)
    t.fd(145)
    t.left(90)
    t.fd(145)
    t.left(90)
    t.fd(145)
    t.left(90)
    t.fd(145)
t.end_fill()
t.right(11.25)
t.color('yellow')
t.fillcolor('yellow')
t.begin_fill()
for _ in range(16):
    t.left(22.5)
    t.fd(125)
    t.left(90)
    t.fd(125)
    t.left(90)
    t.fd(125)
    t.left(90)
    t.fd(125)
t.end_fill()
t.left(11.25)
t.color('white')
t.fillcolor('white')
t.begin_fill()
for _ in range(16):
    t.left(22.5)
    t.fd(107)
    t.left(90)
    t.fd(107)
    t.left(90)
    t.fd(107)
    t.left(90)
    t.fd(107)
t.end_fill()
t.right(11.25)
t.penup()
t.fd(110)
t.pendown()
t.left(90)
t.color('red')
t.fillcolor('red')
t.begin_fill()
t.circle(110)
t.end_fill()
t.penup()
t.left(90)
t.fd(15)
t.right(90)
t.pendown()
t.color('green')
t.fillcolor('green')
t.begin_fill()
t.circle(95)
t.end_fill()
t.color('white')
t.left(90)
t.penup()
t.fd(95)
t.pendown()
t.left(180)
t.color('yellow')
t.fillcolor('yellow')
t.begin_fill()
for _ in range(8):
    t.left(45)
    t.fd(63.63)
    t.left(90)
    t.fd(63.63)
    t.left(90)
    t.fd(63.63)
    t.left(90)
    t.fd(63.63)
t.end_fill()
t.left(22.5)
t.color('violet')
t.fillcolor('violet')
t.begin_fill()
for _ in range(8):
    t.left(45)
    t.fd(63.63)
    t.left(90)
    t.fd(63.63)
    t.left(90)
    t.fd(63.63)
    t.left(90)
    t.fd(63.63)
t.end_fill()
t.left(22.5)
t.left(180)
t.color('black')
t.fillcolor('black')
t.begin_fill()
for _ in range(8):
    t.left(45)
    t.circle(32)
t.end_fill()
t.left(22.5)
t.width(3)
for i in range(8):
    if i%2==0:
        t.color('white')
        t.fillcolor('white')
        t.begin_fill()
        t.left(45)
        t.fd(30)
        t.left(90)
        t.fd(30)
        t.left(90)
        t.fd(30)
        t.left(90)
        t.fd(30)
        t.end_fill()
    else:
        if i==7:
                t.color('gold')
                t.fillcolor('gold')
                t.begin_fill()
                t.left(135)
                t.fd(30)
                t.right(90)
                t.fd(30)
                t.right(90)
                t.fd(14)
                t.right(135)
                t.fd(21.21)
                t.left(104)
                t.fd(30)
                t.end_fill()
        else:
            t.color('gold')
            t.fillcolor('gold')
            t.begin_fill()
            t.left(45)
            t.fd(30)
            t.left(90)
            t.fd(30)
            t.left(90)
            t.fd(30)
            t.left(90)
            t.fd(30)
            t.end_fill()
t.color('black')
t.hideturtle()










