import turtle
t = turtle.Turtle()
t.speed(speed=0)
t.color('black')
t.fillcolor('black')
t.begin_fill()
for i in range(32):
   if i%2==0:
            t.color('black')
            t.fillcolor('black')
            t.begin_fill()
            t.left(11.25)
            t.fd(198)
            t.left(90)
            t.fd(198)
            t.left(90)
            t.fd(198)
            t.left(90)
            t.fd(198)
            t.end_fill()
   else :
            t.color('white')
            t.fillcolor('white')
            t.begin_fill()
            t.left(11.25)
            t.fd(198)
            t.left(90)
            t.fd(198)
            t.left(90)
            t.fd(198)
            t.left(90)
            t.fd(198)
            t.end_fill()
t.left(5.625)
t.color('maroon')
t.fillcolor('maroon')
t.begin_fill()
for _ in range(32):
    t.left(11.25)
    t.fd(184)
    t.left(90)
    t.fd(184)
    t.left(90)
    t.fd(184)
    t.left(90)
    t.fd(184)
t.end_fill()
t.right(5.625)
t.color('red')
t.fillcolor('red')
t.begin_fill()
for _ in range(32):
    t.left(11.25)
    t.fd(169)
    t.left(90)
    t.fd(169)
    t.left(90)
    t.fd(169)
    t.left(90)
    t.fd(169)
t.end_fill()
t.left(5.625)
t.color('orange')
t.fillcolor('orange')
t.begin_fill()
for _ in range(32):
    t.left(11.25)
    t.fd(158)
    t.left(90)
    t.fd(158)
    t.left(90)
    t.fd(158)
    t.left(90)
    t.fd(158)
t.end_fill()
t.right(5.625)
t.color('yellow')
t.fillcolor('yellow')
t.begin_fill()
for _ in range(32):
    t.left(11.25)
    t.fd(148)
    t.left(90)
    t.fd(148)
    t.left(90)
    t.fd(148)
    t.left(90)
    t.fd(148)
t.end_fill()
t.color('white')
t.fillcolor('white')
t.begin_fill()
for _ in range(16):
    t.left(22.5)
    t.circle(99)
t.end_fill()
t.pu()
t.fd(192)
t.pd()
t.left(90)
for i in range(120):
    if i==30 or i==60 or i==90:
        t.color('green')
        t.fillcolor('green')
        t.begin_fill()
        t.left(1.5)
        t.fd(10)
        t.left(90)
        t.fd(10)
        t.left(90)
        t.fd(10)
        t.left(90)
        t.fd(10)
        t.left(90)
        t.fd(5)
        t.end_fill()
        t.color('green')
        t.fillcolor('green')
        t.begin_fill()
        t.left(1.5)
        t.fd(10)
        t.left(90)
        t.fd(10)
        t.left(90)
        t.fd(10)
        t.left(90)
        t.fd(10)
        t.left(90)
        t.fd(5)
        t.end_fill()
    else:
        t.color('gold')
        t.fillcolor('gold')
        t.begin_fill()
        t.left(1.5)
        t.fd(10)
        t.left(90)
        t.fd(10)
        t.left(90)
        t.fd(10)
        t.left(90)
        t.fd(10)
        t.left(90)
        t.fd(5)
        t.end_fill()
        t.color('green')
        t.fillcolor('green')
        t.begin_fill()
        t.left(1.5)
        t.fd(10)
        t.left(90)
        t.fd(10)
        t.left(90)
        t.fd(10)
        t.left(90)
        t.fd(10)
        t.left(90)
        t.fd(5)
        t.end_fill()
t.left(90)
t.pu()
t.fd(190)
t.left(180)
t.pd()
t.color('black')
t.fillcolor('black')
t.begin_fill()
for _ in range(16):
    t.left(22.5)
    t.circle(88)
t.end_fill()
t.color('violet')
t.fillcolor('violet')
t.begin_fill()
for _ in range(8):
    t.left(45)
    t.circle(86)
t.end_fill()
t.left(22.5)
t.color('black')
t.fillcolor('black')
t.begin_fill()
for _ in range(8):
    t.left(45)
    t.circle(88)
t.end_fill()
t.color('gold')
t.fillcolor('gold')
t.begin_fill()
for _ in range(8):
    t.left(45)
    t.circle(86)
t.end_fill()
for i in range(32):
   if i%2==0:
            t.color('green')
            t.fillcolor('green')
            t.begin_fill()
            t.left(11.25)
            t.fd(104)
            t.left(90)
            t.fd(104)
            t.left(90)
            t.fd(104)
            t.left(90)
            t.fd(104)
            t.end_fill()
   else :
            t.color('gold')
            t.fillcolor('gold')
            t.begin_fill()
            t.left(11.25)
            t.fd(104)
            t.left(90)
            t.fd(104)
            t.left(90)
            t.fd(104)
            t.left(90)
            t.fd(104)
            t.end_fill()
t.left(5.625)
t.color('red')
t.fillcolor('red')
t.begin_fill()
for _ in range(32):
    t.left(11.25)
    t.fd(97)
    t.left(90)
    t.fd(97)
    t.left(90)
    t.fd(97)
    t.left(90)
    t.fd(97)
t.end_fill()
t.right(5.625)
t.color('orange')
t.fillcolor('orange')
t.begin_fill()
for _ in range(32):
    t.left(11.25)
    t.fd(81)
    t.left(90)
    t.fd(81)
    t.left(90)
    t.fd(81)
    t.left(90)
    t.fd(81)
t.end_fill()
t.left(5.625)
t.color('yellow')
t.fillcolor('yellow')
t.begin_fill()
for _ in range(32):
    t.left(11.25)
    t.fd(77)
    t.left(90)
    t.fd(77)
    t.left(90)
    t.fd(77)
    t.left(90)
    t.fd(77)
t.end_fill()
t.color('white')
t.fillcolor('white')
t.begin_fill()
for _ in range(16):
    t.left(22.5)
    t.circle(40)
t.end_fill()
t.width(3)
t.color('black')
t.fillcolor('black')
t.begin_fill()
for _ in range(32):
    t.left(11.25)
    t.fd(50)
    t.left(90)
    t.fd(50)
    t.left(90)
    t.fd(50)
    t.left(90)
    t.fd(50)
t.end_fill()
t.color('maroon')
t.fillcolor('maroon')
t.begin_fill()
for _ in range(16):
    t.left(22.5)
    t.circle(25)
t.end_fill()
t.color('red')
t.fillcolor('red')
t.begin_fill()
for _ in range(16):
    t.left(22.5)
    t.circle(20)
t.end_fill()
t.color('orange')
t.fillcolor('orange')
t.begin_fill()
for _ in range(16):
    t.left(22.5)
    t.circle(15)
t.end_fill()
t.color('yellow')
t.fillcolor('yellow')
t.begin_fill()
for _ in range(16):
    t.left(22.5)
    t.circle(10)
t.end_fill()
t.color('white')
t.fillcolor('white')
t.begin_fill()
for _ in range(16):
    t.left(22.5)
    t.circle(5)
t.end_fill()
 



    
    
